plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
}

group = 'homelab'
version = '0.0.1-SNAPSHOT'
description = 'Fitness Tracker'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	implementation 'org.springframework.boot:spring-boot-starter-logging'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	// testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
  testImplementation 'org.mockito:mockito-core:5.21.0'
  testImplementation 'org.mockito:mockito-junit-jupiter:5.21.0'
  // Other test deps like JUnit 5
  testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'
}

test {
	useJUnitPlatform()
  def mockitoCore = configurations.testRuntimeClasspath.resolvedConfiguration.resolvedArtifacts.find {
    it.moduleVersion.id.name == 'mockito-core'
  }?.file  
  if (mockitoCore) {
    jvmArgs "-javaagent:${mockitoCore.absolutePath}"
  }
  finalizedBy jacocoTestReport
}

jacocoTestReport {
  reports {
    xml.required = false
    html.required = true
    csv.required = false
  }
}

