server:
  port: 8080

spring:
  application:
    name: ftrack
  mongodb:
    uri: mongodb+srv://ftrack_owner:3ZmhzZiPuIAnFEUl@0.af9yoov.mongodb.net/ftrackdb?appName=Cluster0
  #host: localhost
    #port: 27017
    #database: ftrackdb

logging:
  level:
    org.springframework.data.mongodb: INFO
    org.mongodb.driver: INFO
